# -*- coding: utf-8 -*-
"""linearsearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Zs5cf4yquHacn0CSQ3qbPPmxBRIOqAm
"""

import time
import matplotlib.pyplot as plt

# Linear Search Function
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

# Function to perform the experiment and record time
def time_linear_search(n):
    arr = list(range(n))  # Create a list with n elements
    target = n - 1  # Let's search for the last element
    start_time = time.time()
    linear_search(arr, target)
    end_time = time.time()
    return end_time - start_time

# Number of elements to test
n_values = [10, 50, 100, 500, 1000, 5000, 10000]
times = [time_linear_search(n) for n in n_values]

# Plotting the graph
plt.plot(n_values, times, marker='o')
plt.xlabel('Number of Elements (n)')
plt.ylabel('Time Taken (seconds)')
plt.title('Time Taken for Linear Search vs Number of Elements')
plt.grid(True)
plt.show()